name: Padavan

on:
  push:

  schedule:
    - cron: '0 0 * * 0'

env:
  MODEL: "CR660x K2P PSG1218 RM2100" #编译型号
  NAME: padavan #镜像名称

jobs:
  cache:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Get COMMIT ID
        run: |
          echo "COMMIT=$(git ls-remote https://github.com/padavanonly/rt-n56u.git HEAD | awk '{print $1}')" >> $GITHUB_ENV
          touch ~/.cache
          
      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: ${{ env.COMMIT }}

  padavan:
    runs-on: ubuntu-latest
    needs: cache
    if: needs.cache.outputs.cache-hit != 'true'
    steps:
      - name: Get DATE
        run: echo "DATE=$(date +%F)" >> $GITHUB_ENV

      - name: Build
        run: |
          git clone --depth=1 https://github.com/padavanonly/rt-n56u.git /opt/rt-n56u
          sudo apt-get install autopoint
          cd /opt/rt-n56u/toolchain-mipsel
          sh dl_toolchain.sh >/dev/null 2>&1
          mkdir -p /opt/images
          cd ../trunk
          sed -i "3c FIRMWARE_BUILDS_REV=$DATE" versions.inc
          sed -i '/### Enable USB support/,$d' configs/templates/*.config
          sed -i 's/CONFIG_KERNEL_NO_COMPRESS=y/CONFIG_KERNEL_NO_COMPRESS=n/g' configs/templates/*.config
          sed -i 's/CONFIG_FIRMWARE_INCLUDE_SFE=y/CONFIG_FIRMWARE_INCLUDE_SFE=n/g' configs/templates/*.config
          sed -i 's/"sshd_enable", "1"/"sshd_enable", "0"/g' user/shared/defaults.c
          sed -i 's/"lltd_enable", "1"/"lltd_enable", "0"/g' user/shared/defaults.c
          sed -i 's/"crond_enable", "1"/"crond_enable", "0"/g' user/shared/defaults.c
          for m in $MODEL; do fakeroot ./build_firmware_ci $m; \
          if [ $? = 0 ]; then mv -f images/*.trx /opt/images/$m-$DATE.trx; else exit 1; fi; \
          ./clear_tree_simple >/dev/null 2>&1; done
          cd /opt/images
          echo "# 型号: ${{ env.MODEL }}" > README.md
          echo "MD5：" >> README.md
          echo '```' >> README.md
          md5sum *.trx >> README.md
          echo '```' >> README.md
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: /opt/images/README.md
          tag_name: ${{ env.DATE }}
          files: /opt/images/*.trx

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: waterlemons2k
          password: ${{ secrets.TOKEN }}
        
      - name: Build and push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: waterlemons2k/${{ env.NAME }}
